# Generated by Django 6.0 on 2026-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
