# Generated by Django 6.0 on 2026-01-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hostel_order_delivered_at_order_delivery_proof_and_more'),
        ('userauths', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cafeteria',
            field=models.ForeignKey(blank=True, help_text='Cafeteria this user belongs to (for managers and waiters)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.cafeteria'),
        ),
    ]
