# Generated by Django 6.0 on 2026-01-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_cafeteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cafeteria',
        ),
    ]
