# Generated by Django 6.0 on 2025-12-21 18:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food item name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('stock_qty', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(help_text='Food item description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Food item price', max_digits=10)),
                ('image', models.FileField(blank=True, help_text='Food item image', null=True, upload_to='food_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the food item is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True)),
                ('orders', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor/restaurant name', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Vendor description')),
                ('address', models.TextField(blank=True, help_text='Vendor physical address', null=True)),
                ('logo', models.FileField(blank=True, help_text='Vendor logo image', null=True, upload_to='vendor_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vendor is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity of this item', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cart_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Cart owner', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(help_text='Food item in cart', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.fooditem')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total order amount', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Order status', max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_address', models.TextField(help_text='Delivery address for this order')),
                ('payment_status', models.CharField(choices=[('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Stripe transaction ID or payment reference', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('delivery_batch', models.CharField(blank=True, help_text='Delivery batch', max_length=200)),
                ('order_pin', models.IntegerField(blank=True, help_text='Order pin (4 digits)', null=True, unique=True)),
                ('approved', models.BooleanField(default=False, help_text='Whether the order has been approved')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Primary vendor (nullable for multi-vendor orders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total of Product price * Product Qty', max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated Service Fee = service_fee * total (paid by buyer to platform)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Grand Total of all amount listed above', max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('food_item', models.ForeignKey(help_text='Food item in order', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.fooditem')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('vendor', models.ForeignKey(help_text='Order vendor', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor that offers this food item', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('vendor', 'name')},
        ),
    ]
