# Generated by Django 6.0 on 2026-01-05 20:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField(default='08:00')),
                ('cutoff_time', models.TimeField(default='18:00')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food item name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('stock_qty', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(help_text='Food item description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Food item price', max_digits=10)),
                ('image', models.FileField(blank=True, help_text='Food item image', null=True, upload_to='food_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the food item is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True)),
                ('orders', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostel name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Hostel slug', max_length=100, unique=True)),
                ('description', models.TextField(default='Unknown', help_text='Hostel description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Default delivery fee in Naira (e.g., 500.00)', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Default service fee in Naira (e.g., 100.00)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity of this item', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cart_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('user', models.OneToOneField(help_text='Cart owner', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(blank=True, help_text='Food item in cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.fooditem')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total order amount', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Order status', max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee from SiteSettings', max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee from SiteSettings', max_digits=12)),
                ('total_pack_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Total packaging fees for all vendors in this order', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for the order', max_length=200)),
                ('room_address', models.CharField(blank=True, help_text='Room number or room address', max_length=200)),
                ('delivery_time', models.CharField(blank=True, help_text='Preferred delivery time', max_length=100)),
                ('payment_status', models.CharField(choices=[('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Stripe transaction ID or payment reference', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('order_pin', models.IntegerField(blank=True, help_text='Order pin (4 digits)', null=True, unique=True)),
                ('approved', models.BooleanField(default=False, help_text='Whether the order has been approved')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('delivery_batch', models.ForeignKey(blank=True, help_text='Delivery batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverybatch')),
                ('hostel', models.ForeignKey(blank=True, help_text='Hostel associated with this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.hostel')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostels', models.ManyToManyField(blank=True, help_text='Hostels this rider delivers to', related_name='riders', to='core.hostel')),
                ('user', models.OneToOneField(help_text='User account for this rider', on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor/restaurant name', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Vendor description')),
                ('address', models.TextField(blank=True, help_text='Vendor physical address', null=True)),
                ('logo', models.FileField(blank=True, help_text='Vendor logo image', null=True, upload_to='vendor_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vendor is currently active')),
                ('pack_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Packaging fee per order from this vendor', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='User account associated with this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total of Product price * Product Qty', max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated Service Fee = service_fee * total (paid by buyer to platform)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Grand Total of all amount listed above', max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('food_item', models.ForeignKey(help_text='Food item in order', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.fooditem')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('vendor', models.ForeignKey(help_text='Order vendor', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Primary vendor (nullable for multi-vendor orders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor that offers this food item', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.vendor'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Room number e.g 1, 2, 3, 4', max_length=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hostel')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('hostel', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('vendor', 'name')},
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this item', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Parent cart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('user', models.ForeignKey(help_text='Cart item user', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(blank=True, help_text='Food item in cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.fooditem')),
                ('vendor', models.ForeignKey(help_text='Cart item vendor', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'unique_together': {('cart', 'food_item')},
            },
        ),
    ]
