# Generated by Django 6.0 on 2025-12-14 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(help_text='Cart owner', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='Parent cart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(help_text='Cart item user', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='food_item',
            field=models.ForeignKey(help_text='Food item in cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='food_item',
            field=models.ForeignKey(help_text='Food item in cart', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Order customer', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(help_text='Food item in order', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(help_text='Order vendor', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(help_text='Order vendor', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor that offers this food item', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='vendor',
            field=models.ForeignKey(help_text='Cart item vendor', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('vendor', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'food_item')},
        ),
    ]
