# Generated by Django 6.0 on 2025-12-29 22:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this item', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Parent cart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('food_item', models.ForeignKey(help_text='Food item in cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.fooditem')),
                ('user', models.ForeignKey(help_text='Cart item user', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='Cart item vendor', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'unique_together': {('cart', 'food_item')},
            },
        ),
    ]
