# Generated by Django 6.0 on 2025-12-14 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Order date'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_batch',
            field=models.CharField(blank=True, help_text='Delivery batch', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pin',
            field=models.IntegerField(blank=True, help_text='Order pin (4 digits)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_id',
            field=models.CharField(blank=True, help_text='Unique item identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
