# Generated by Django 6.0 on 2025-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_date_order_delivery_batch_order_order_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether the order has been approved'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_pin',
            field=models.IntegerField(blank=True, help_text='Order pin', max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Vendor physical address', null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
