# Generated by Django 6.0 on 2025-12-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Default delivery fee in Naira (e.g., 500.00)', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Default service fee in Naira (e.g., 100.00)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
