# Generated by Django 6.0 on 2025-12-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_approved_alter_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_pin',
            field=models.IntegerField(blank=True, help_text='Order pin (4 digits)', null=True, unique=True),
        ),
    ]
