# Generated by Django 6.0 on 2025-12-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for the order', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Preferred delivery time', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='room_address',
            field=models.CharField(blank=True, help_text='Room number or room address', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_batch',
            field=models.CharField(blank=True, choices=[('1pm', '1pm'), ('6pm', '6pm')], help_text='Delivery batch (1pm or 6pm)', max_length=10),
        ),
    ]
