# Generated by Django 6.0 on 2025-12-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_customer_name_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee from SiteSettings', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee from SiteSettings', max_digits=12),
        ),
    ]
