# Generated by Django 6.0 on 2025-12-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_order_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Primary vendor (nullable for multi-vendor orders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendor'),
        ),
    ]
