# Generated by Django 6.0 on 2026-01-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_delivery_fee_alter_order_service_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Daniel Hall', 'Daniel Hall'), ('Peter Hall', 'Peter Hall'), ('Mary Hall', 'Mary Hall'), ('Johnson Hall', 'Johnson Hall')], help_text='Select your hostel', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_batch',
            field=models.CharField(blank=True, choices=[('2pm', '2pm'), ('6pm', '6pm')], help_text='Delivery batch (1pm or 6pm)', max_length=10),
        ),
    ]
