# Generated by Django 6.0 on 2026-01-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_delivery_time_order_hostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='food_item',
            field=models.ForeignKey(blank=True, help_text='Food item in cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.fooditem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('NH', 'NH'), ('Extension', 'Extension'), ('NH Girls A', 'NH Girls A'), ('NH Girls B', 'NH Girls B'), ('NH Girls C', 'NH Girls C'), ('288', '288'), ('Saddler', 'Saddler'), ('Storey Building', 'Storey Building'), ('UPE 1', 'UPE 1'), ('UPE 2', 'UPE 2'), ('UPE 3', 'UPE 3'), ('300 Bedspace', '300 Bedspace'), ("VC's Lodge", "VC's Lodge"), ('Block Hostels', 'Block Hostels')], help_text='Select your hostel', max_length=100),
        ),
    ]
