# Generated by Django 6.0 on 2026-01-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cartitem_food_item_alter_order_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Preferred delivery time', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='food_item',
            field=models.ForeignKey(blank=True, help_text='Food item in cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.fooditem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_batch',
            field=models.CharField(blank=True, choices=[('1pm', '1pm'), ('6pm', '6pm')], help_text='Delivery batch (1pm or 6pm)', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='hostel',
            field=models.TextField(help_text='Delivery address for this order'),
        ),
    ]
