# Generated by Django 6.0 on 2026-01-04 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_delivery_address_order_delivery_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostel name', max_length=200, unique=True)),
                ('address', models.TextField(blank=True, help_text='Hostel address', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the hostel is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof',
            field=models.TextField(blank=True, help_text='Delivery proof (OTP, signature, or photo URL)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hostel_text',
            field=models.TextField(blank=True, help_text='Hostel text (legacy field, use hostel FK instead)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if order is cancelled', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='Waiter assigned to deliver this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Assigned', 'Assigned to Waiter'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Order status', max_length=20),
        ),
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cafeteria name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Cafeteria description', null=True)),
                ('address', models.TextField(blank=True, help_text='Cafeteria physical address', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the cafeteria is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(blank=True, help_text='Cafeteria manager (one per cafeteria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cafeteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cafeteria',
                'verbose_name_plural': 'Cafeterias',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cafeteria',
            field=models.ForeignKey(blank=True, help_text='Cafeteria handling this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.cafeteria'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='Delivery hostel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.hostel'),
        ),
    ]
