# Generated by Django 6.0 on 2026-01-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hostel_order_delivered_at_order_delivery_proof_and_more'),
    ]

    operations = [
    ]
