# Generated by Django 6.0 on 2026-01-04 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_create_default_hostel'),
        ('userauths', '0007_remove_user_cafeteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cafeteria',
        ),
        migrations.AlterField(
            model_name='order',
            name='hostel',
            field=models.TextField(default='Unknown', help_text='Delivery address for this order'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_proof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hostel_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rejected_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account associated with this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Order status', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cafeteria',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
