# Generated by Django 6.0 on 2026-01-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_cafeteria_alter_order_hostel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Batch name (e.g., '1pm Delivery')", max_length=50)),
                ('cutoff_time', models.TimeField(help_text='Time after which this batch is unavailable')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostel name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Hostel slug', max_length=100, unique=True)),
                ('rooms', models.IntegerField(default=100, help_text='Total number of rooms')),
                ('description', models.TextField(default='Unknown', help_text='Hostel description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_batch',
            field=models.ForeignKey(blank=True, help_text='Delivery batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverybatch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='Hostel associated with this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.hostel'),
        ),
    ]
