# Generated by Django 6.0 on 2026-01-05 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_deliverybatch_hostel_alter_order_delivery_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostels', models.ManyToManyField(blank=True, help_text='Hostels this rider delivers to', related_name='riders', to='core.hostel')),
                ('user', models.OneToOneField(help_text='User account for this rider', on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
            },
        ),
    ]
