# Generated by Django 6.0 on 2026-01-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='rooms',
        ),
        migrations.AddField(
            model_name='order',
            name='total_pack_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total packaging fees for all vendors in this order', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pack_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Packaging fee per order from this vendor', max_digits=10),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Room number e.g 1, 2, 3, 4', max_length=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hostel')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('hostel', 'number')},
            },
        ),
    ]
